import os
from dotenv import load_dotenv

load_dotenv()

BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN')
API_BASE_URL = os.getenv('API_BASE_URL', 'http://backend:8080/api')

SURNAME, NAME, PATRONYMIC, ROLE, GROUP_OR_COMPANY = range(5)

CREATE_EVENT_NAME, CREATE_EVENT_DESC, CREATE_EVENT_DATE, CREATE_EVENT_DEADLINE, CREATE_EVENT_LOCATION = range(5, 10)

EDIT_EVENT_SELECT, EDIT_EVENT_FIELD, EDIT_EVENT_VALUE = range(10, 13)

DECLINE_USER_REASON = range(13, 14)

STUDENT_ROLE = 'STUDENT'
MANAGER_ROLE = 'MANAGER'
ADMIN_ROLE = 'ADMIN'

AVAILABLE_ROLES = [STUDENT_ROLE, MANAGER_ROLE]

COMPANIES_PER_PAGE = 5
